import { defineMeta } from "blume";

export default defineMeta({
  title: "Plugins",
  icon: "plug",
  pages: [
    "index",
    "writing-plugins",
    "operations",
    "input-rules",
    "example-plugin",
    "rich-text",
    "code",
    "image",
    "embed",
    "bookmark",
    "file",
    "video",
    "audio",
    "columns",
    "page",
    "table-of-contents",
    "block-handles",
    "block-menu",
    "slash-menu",
    "toolbar",
    "markdown-shortcuts",
    "arrow-move",
    "find",
    "mention",
    "page-link",
  ],
});
