import type * as V from './vendor/yjs/dts/index.js';

/** The engine symbols edytor calls — the keys of `Y` in `engine.js`. */
export type EngineSymbol =
	| 'Doc'
	| 'Node'
	| 'UndoManager'
	| 'Item'
	| 'RangeCursor'
	| 'transact'
	| 'applyUpdate'
	| 'encodeStateAsUpdate'
	| 'encodeStateVector'
	| 'decodeStateVector'
	| 'decodeUpdate'
	| 'decodeUpdateV2'
	| 'UpdateEncoderV1'
	| 'writeIdSet'
	| 'mergeUpdates'
	| 'applyUpdateV2'
	| 'encodeStateAsUpdateV2'
	| 'mergeUpdatesV2'
	| 'convertUpdateFormatV2ToV1'
	| 'UpdateDecoderV1'
	| 'UpdateEncoderV2'
	| 'Skip'
	| 'findIndexSS'
	| 'isKeptReplaced'
	| 'createRelativePositionFromTypeIndex'
	| 'createRelativePositionFromJSON'
	| 'createAbsolutePositionFromRelativePosition'
	| 'relativePositionToJSON'
	| 'createIdSet'
	| 'diffIdSet'
	| 'insertIntoIdSet'
	| 'createIdMap'
	| 'insertIntoIdMap'
	| 'createContentMap'
	| 'decodeContentMap'
	| 'iterateStructsByIdSet'
	| 'getItemCleanStart'
	| 'redoItem'
	| 'ContentAny'
	| 'createID';

export declare const Y: Pick<typeof V, EngineSymbol>;
